### ISSUE TITLE
Any and All implementations

### ISSUE THREAD

**Issue by sea1jxr** [Jason3S/GenSequence#1]
Would you be open to the addition of any() and all() functions?

**Comment by Jason3S** [comment]
Yes.  Please make a pull request.

**Comment by Jason3S** [comment]
Thank you.  If you have any other operators, please do another pull request.

**Comment by sea1jxr** [comment]
I have a few more that I am thinking about adding.  min, max, except, and union are pretty handy.

**Comment by Jason3S** [comment]
Great! Can you make one request for each one?  That way it is easier to review.

**Comment by sea1jxr** [comment]
sure, sounds wise.
